-- MySQL Script generated by MySQL Workbench
-- Mon Oct 18 12:51:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema moviebookings
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `moviebookings` ;

-- -----------------------------------------------------
-- Schema moviebookings
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moviebookings` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `moviebookings` ;

-- -----------------------------------------------------
-- Table `moviebookings`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`state` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`state` (
  `state` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`state`),
  UNIQUE INDEX `state_UNIQUE` (`state` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `moviebookings`.`state` (`state`)
VALUES (''),('AL'),('AK'),('AZ'),('AR'),('CA'),('CO'),('CT'),
('DC'),('DE'),('FL'),('GA'),('HI'),('ID'),('IL'),('IN'),
('IA'),('KS'),('KY'),('LA'),('ME'),('MD'),('MA'),('MI'),
('MN'),('MS'),('MO'),('MT'),('NE'),('NV'),('NH'),('NJ'),
('NM'),('NY'),('NC'),('ND'),('OH'),('OK'),('OR'),('PA'),
('RI'),('SC'),('SD'),('TN'),('TX'),('UT'),('VT'),('VA'),
('WA'),('WV'),('WI'),('WY');


-- -----------------------------------------------------
-- Table `moviebookings`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`address` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`address` (
  `addressID` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `zipcode` VARCHAR(10) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`addressID`),
  UNIQUE INDEX `addressID_UNIQUE` (`addressID` ASC) VISIBLE,
  INDEX `state_idx` (`state` ASC) VISIBLE,
  CONSTRAINT `state`
    FOREIGN KEY (`state`)
    REFERENCES `moviebookings`.`state` (`state`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `moviebookings`.`promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`promotion` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`promotion` (
  `promoID` INT NOT NULL AUTO_INCREMENT,
  `discount` DOUBLE NULL DEFAULT NULL,
  `code` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`promoID`),
  UNIQUE INDEX `promoID_UNIQUE` (`promoID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




-- -----------------------------------------------------
-- Table `moviebookings`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`user` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `email_confirmed` TINYINT(1) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `promotions` TINYINT(1) NULL DEFAULT NULL,
  `shippingAddressID` INT NULL DEFAULT NULL,
  `isAdmin` TINYINT(1) NOT NULL,
  `isSuspended` TINYINT(1) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE,
  INDEX `shippingAddressID_idx` (`shippingAddressID` ASC) VISIBLE,
  CONSTRAINT `shippingAddressID`
    FOREIGN KEY (`shippingAddressID`)
    REFERENCES `moviebookings`.`address` (`addressID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviebookings`.`paymentcard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`paymentcard` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`paymentcard` (
  `paymentID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `cardType` VARCHAR(20) NOT NULL,
  `cardNumber` BIGINT NOT NULL,
  `billingAddressID` INT NULL DEFAULT NULL,
  `expirationMonth` INT NULL DEFAULT NULL,
  `expirationYear` INT NULL DEFAULT NULL,
  `userID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`paymentID`),
  UNIQUE INDEX `paymentID_UNIQUE` (`paymentID` ASC) VISIBLE,
  INDEX `billingAddressID_idx` (`billingAddressID` ASC) VISIBLE,
  INDEX `userID_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `billingAddressID`
    FOREIGN KEY (`billingAddressID`)
    REFERENCES `moviebookings`.`address` (`addressID`),
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `moviebookings`.`user` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviebookings`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`genre` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`genre` (
  `genreID` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`genreID`),
  UNIQUE INDEX `genreID_UNIQUE` (`genreID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `moviebookings`.`genre` (`genre`)
VALUES ('Crime'), ('Drama'), ('Adventure'), ('Thriller'), ('Horror'), 
('Action'), ('Fantasy'), ('Sci-Fi'), ('Comedy'), ('War'), ('Mystery'),
('Biography'), ('History'), ('Romance'), ('Family'), ('Musical'), ('Sport'), 
('Music'), ('Animation'), ('Western'), ('Documentary'), ('News');

-- -----------------------------------------------------
-- Table `moviebookings`.`usrating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`usrating` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`usrating` (
  `ratingID` INT NOT NULL AUTO_INCREMENT,
  `ratingCode` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`ratingID`),
  UNIQUE INDEX `ratingID_UNIQUE` (`ratingID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `moviebookings`.`usrating` (`ratingCode`)
VALUES ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17');

-- -----------------------------------------------------
-- Table `moviebookings`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`movie` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`movie` (
  `movieID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `genreID` INT NULL DEFAULT NULL,
  `cast` TEXT NULL DEFAULT NULL,
  `director` VARCHAR(45) NULL DEFAULT NULL,
  `producer` VARCHAR(45) NULL DEFAULT NULL,
  `synopsis` TEXT NULL DEFAULT NULL,
  `reviews` DOUBLE NULL DEFAULT NULL,
  `duration` INT NULL DEFAULT NULL,
  `trailerPictureLink` VARCHAR(4500) NULL DEFAULT NULL,
  `trailerVideoLink` VARCHAR(4500) NULL DEFAULT NULL,
  `ratingID` INT NULL DEFAULT NULL,
  `release_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`movieID`),
  UNIQUE INDEX `movieID_UNIQUE` (`movieID` ASC) VISIBLE,
  INDEX `ratingID_idx` (`ratingID` ASC) VISIBLE,
  INDEX `genreID_idx` (`genreID` ASC) VISIBLE,
  CONSTRAINT `genreID`
    FOREIGN KEY (`genreID`)
    REFERENCES `moviebookings`.`genre` (`genreID`),
  CONSTRAINT `ratingID`
    FOREIGN KEY (`ratingID`)
    REFERENCES `moviebookings`.`usrating` (`ratingID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviebookings`.`theatre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`theatre` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`theatre` (
  `buildingID` INT NOT NULL,
  PRIMARY KEY (`buildingID`),
  UNIQUE INDEX `buildingID_UNIQUE` (`buildingID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviebookings`.`showroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`showroom` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`showroom` (
  `showroomID` INT NOT NULL,
  `theatreID` INT NOT NULL,
  `noOfSeats` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`showroomID`),
  INDEX `theatreID_idx` (`theatreID` ASC) VISIBLE,
  UNIQUE INDEX `showroomID_UNIQUE` (`showroomID` ASC) VISIBLE,
  CONSTRAINT `theatreID`
    FOREIGN KEY (`theatreID`)
    REFERENCES `moviebookings`.`theatre` (`buildingID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviebookings`.`showing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`showing` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`showing` (
  `showID` INT NOT NULL AUTO_INCREMENT,
  `showRoomID` INT NOT NULL,
  `movieID` INT NOT NULL,
  `datetime` DATETIME NULL DEFAULT NULL,
  `duration` INT NULL DEFAULT NULL,
  PRIMARY KEY (`showID`),
  INDEX `movieID` (`movieID` ASC) VISIBLE,
  INDEX `showRoomID_idx` (`showRoomID` ASC) VISIBLE,
  UNIQUE INDEX `showID_UNIQUE` (`showID` ASC) VISIBLE,
  CONSTRAINT `movieID`
    FOREIGN KEY (`movieID`)
    REFERENCES `moviebookings`.`movie` (`movieID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviebookings`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`booking` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`booking` (
  `bookingID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `showingID` INT NULL DEFAULT NULL,
  `paymentID` INT NULL DEFAULT NULL,
  `noOfTickets` INT NULL DEFAULT NULL,
  `totalPrice` DOUBLE NULL DEFAULT NULL,
  `promoID` INT NULL DEFAULT NULL,
  `bookingTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`bookingID`),
  UNIQUE INDEX `bookingID_UNIQUE` (`bookingID` ASC) VISIBLE,
  INDEX `customerID_idx` (`userID` ASC) VISIBLE,
  INDEX `showingID_idx` (`showingID` ASC) VISIBLE,
  INDEX `paymentID_idx` (`paymentID` ASC) VISIBLE,
  CONSTRAINT `id_promo`
    FOREIGN KEY (`promoID`)
    REFERENCES `moviebookings`.`promotion` (`promoID`),
  CONSTRAINT `id_showing`
    FOREIGN KEY (`showingID`)
    REFERENCES `moviebookings`.`showing` (`showID`),
  CONSTRAINT `id_user`
    FOREIGN KEY (`userID`)
    REFERENCES `moviebookings`.`user` (`userID`),
  CONSTRAINT `paymentID`
    FOREIGN KEY (`paymentID`)
    REFERENCES `moviebookings`.`paymentcard` (`paymentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviebookings`.`tickettype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`tickettype` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`tickettype` (
  `ticketTypeID` INT NOT NULL AUTO_INCREMENT,
  `price` FLOAT NULL DEFAULT NULL,
  `ticketTypeName` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ticketTypeID`),
  UNIQUE INDEX `ticketTypeID_UNIQUE` (`ticketTypeID` ASC) VISIBLE,
  UNIQUE INDEX `ticketTypeName_UNIQUE` (`ticketTypeName` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `moviebookings`.`tickettype` (`ticketTypeName`, `price`)
VALUES ('Adult', 8), ('Senior', 13), ('Child', 10);

-- -----------------------------------------------------
-- Table `moviebookings`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`ticket` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`ticket` (
  `ticketID` INT NOT NULL AUTO_INCREMENT,
  `typeID` INT NOT NULL,
  `bookingID` INT NOT NULL,
  `seatID` INT NOT NULL,
  PRIMARY KEY (`ticketID`),
  INDEX `bookingID_idx` (`bookingID` ASC) VISIBLE,
  INDEX `seatID_idx` (`seatID` ASC) VISIBLE,
  INDEX `typeID_idx` (`typeID` ASC) VISIBLE,
  UNIQUE INDEX `ticketID_UNIQUE` (`ticketID` ASC) VISIBLE,
  CONSTRAINT `bookingID`
    FOREIGN KEY (`bookingID`)
    REFERENCES `moviebookings`.`booking` (`bookingID`),
  CONSTRAINT `seatID`
    FOREIGN KEY (`seatID`)
    REFERENCES `moviebookings`.`seat` (`seatID`),
  CONSTRAINT `typeID`
    FOREIGN KEY (`typeID`)
    REFERENCES `moviebookings`.`tickettype` (`ticketTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviebookings`.`seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`seat` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`seat` (
  `seatID` INT NOT NULL,
  `rowLetter` character NOT NULL,
  `seatNum` INT NOT NULL,
  `showRoomID` INT NOT NULL,
  `ticketID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`seatID`),
  UNIQUE INDEX `seatID_UNIQUE` (`seatID` ASC) VISIBLE,
  UNIQUE INDEX `ticketID_UNIQUE` (`ticketID` ASC) VISIBLE,
  INDEX `showRoomID_idx` (`showRoomID` ASC) VISIBLE,
  CONSTRAINT `showRoomID`
    FOREIGN KEY (`showRoomID`)
    REFERENCES `moviebookings`.`showroom` (`showroomID`),
  CONSTRAINT `ticketID`
    FOREIGN KEY (`ticketID`)
    REFERENCES `moviebookings`.`ticket` (`ticketID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviebookings`.`bookingfees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`bookingfees` ;

CREATE TABLE IF NOT EXISTS `moviebookings`.`bookingfees` (
  `bookingFeeID` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`bookingFeeID`),
  UNIQUE INDEX `booking_fee_ID_UNIQUE` (`bookingFeeID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `moviebookings`.`bookingfees` (`price`) VALUES (0);


-- -----------------------------------------------------
-- Table `moviebookings`.`salts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviebookings`.`salts` ;

CREATE TABLE `salts` (
  `email` varchar(100) NOT NULL,
  `salt` varchar(100) NOT NULL,
  PRIMARY KEY (`email`))

ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;